[package]
name = "paperpass"
version = "1.1.12"
edition = "2024"

[dependencies]
chrono = "0.4.45"
colored = "3.1.1"
crossterm = "0.29.0"
csv = "1.4.0"
passwords = "3.1.18"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
toml = "1.1.5"
totp-rs = { version = "6.0.0", features = ["otpauth"] }

[build-dependencies]
chrono = "0.4.45"

# optimize size
# cargo build --profile release-small
[profile.release-small]
inherits = "release"
strip = "debuginfo"
opt-level = 's'
lto = true
codegen-units = 1

