name: build

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: codeberg-small
    steps:
    - uses: actions/checkout@v5
    - name: rust setup
      run: | 
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        . "$HOME/.cargo/env"
        rustc --version
        cargo b -r
        cargo t

    - name: Run Build
      run: cargo b -r

    - name: Run Tests
      run: cargo t 
