name: build

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: codeberg-tiny
    container: archlinux:latest

    steps:
      - name: Create resolv.conf
        run: |
          set -ex
          echo 'nameserver 194.242.2.4' >/etc/resolv.conf
          echo 'nameserver 194.242.2.3' >>/etc/resolv.conf

      - name: Install dependencies
        run: pacman --noconfirm -Syu && pacman --needed --noconfirm -S base-devel cmake ninja curl jq

      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v5

      - name: Run Build
        run: |
          uname -a
          rustc --version

      - name: Run Build
        run: cargo b -r

      - name: Run Tests
        run: cargo t 
