name: build

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: codeberg-tiny
    container: archlinux:latest

    steps:
    - uses: actions/checkout@v4

    # - name: install prerequisites
    #   run: |
    #     cargo install diceware
    #     command -v diceware

    - name: Run Build
      run: |
        rustc --version

    - name: Run Build
      run: cargo b -r

    - name: Run Tests
      run: cargo t 
